---
- name: Retrieve ec2 facts
  ec2_facts:
  when: telegraf_aws_tags

- name: Retrieve all ec2 tags on the instance
  ec2_tag:
    region: '{{ ansible_ec2_placement_region }}'
    resource: '{{ ansible_ec2_instance_id }}'
    state: list
  when: telegraf_aws_tags
  register: ec2_tags

- include: configure-linux.yml
  become: true
  when: ansible_os_family != "Windows"

- include: configure-windows.yml
  when: ansible_os_family == "Windows"
