
- name: Start the Telegraf service
  service:
    name: telegraf
    state: started
    enabled: yes
  # Only care to check the status if the state changed to 'started'
  notify:
    - "pause"
    - "check status"
    - "assert running"
  become: true
  when: ansible_os_family != "Windows"

- block:
    - name: Check if Telegraf is running currently
      win_shell: Get-Service telegraf | ConvertTo-Json -depth 1
      register: telegraf_running

    - name: Stop Telegraf first if it's running
      win_shell: net stop telegraf
      when: (telegraf_running.stdout | from_json).Status == 4
      ignore_errors: yes

    - name: Start the Telegraf service
      win_shell: net start telegraf
      notify:
        - "pause"
        - "windows check status"
        - "assert running"
  when: ansible_os_family == "Windows"
